---
- hosts: leaf,spine
  user: cumulus
  become: yes
  become_method: sudo
  tasks:
    - name: uncomment early access repo
      lineinfile: >
        dest=/etc/apt/sources.list
        regexp="#deb     http://repo3.cumulusnetworks.com/repo CumulusLinux-3-early-access cumulus"
        line="deb     http://repo3.cumulusnetworks.com/repo CumulusLinux-3-early-access cumulus"
        state=present

    - name: uncomment early access repo sources
      lineinfile: >
        dest=/etc/apt/sources.list
        regexp="#deb-src http://repo3.cumulusnetworks.com/repo CumulusLinux-3-early-access cumulus"
        line="deb-src http://repo3.cumulusnetworks.com/repo CumulusLinux-3-early-access cumulus"
        state=present

    - name: install eau8 of quagga
      apt: name="cumulus-evpn" update_cache=yes

    - name: upgrade quagga
      shell: "sudo apt-get upgrade -y --force-yes -o Dpkg::Options::='--force-confnew'"

