# This command actually restarts quagga. This command will actually drop all
# routes currently in progress, so this will interrupt networking currently in
# place.
- name: restart snmpd
  service: name=snmpd state=restarted
  notify: check snmpd

- name: enable snmpd
  service: name=snmpd state=started enabled=yes

- name: check snmpd
  shell: systemctl status snmpd.service
  register: snmpresult
  when: node[ansible_hostname].snmp is defined
  notify: debug snmpd

- name: debug snmpd
  debug: var=snmpresult
  when: node[ansible_hostname].snmp is defined

- name: restart snmpd mgmt vrf
  command: systemctl stop snmpd.service
  notify: stop snmpd mgmt vrf

- name: stop snmpd mgmt vrf
  command: systemctl disable snmpd.service
  notify: start snmpd mgmt vrf

- name: start snmpd mgmt vrf
  command: systemctl start snmpd@mgmt
  notify: enable snmpd mgmt vrf

- name: enable snmpd mgmt vrf
  command: systemctl enable snmpd@mgmt
  notify: check snmpd
