# This writes configuration to the vxrd.conf and vxsnd.conf configuration file using the
# information in group_vars/all.
- name: configure LNV service node vxsnd.conf configuration
  template: src=vxsnd.conf.j2 dest=/etc/vxsnd.conf
  notify:
    - enable and restart vxsnd
  when: (node[ansible_hostname].LNV.service_node is defined)
  tags:
    - vxlan_setup
  
- name: Enable VxSND Service for Subsequent Reboots
  service: name=vxsnd enabled=yes state=started
  when: (node[ansible_hostname].LNV.service_node is defined)
  tags:
    - vxlan_setup

- name: check status to see if vxsnd service is running
  shell: systemctl status vxsnd.service | grep Active
  register: vxsnd
  notify: stop and start vxsnd.service manually (1/2)
  when: (node[ansible_hostname].LNV.service_node is defined)
  tags:
    - vxlan_setup

- name: Enable VxRD Service for Subsequent Reboots
  service: name=vxrd enabled=yes state=started
  when: (node[ansible_hostname].LNV.registration_node is defined)  
  tags:
    - vxlan_setup

- name: check status to see if vxrd is running
  shell: systemctl status vxrd.service | grep Active
  register: vxrd
  notify: stop and start vxrd.service manually (1/2)
  when: (node[ansible_hostname].LNV.registration_node is defined)  
  tags:
    - vxlan_setup

